[tool.black]
line-length = 88

[tool.isort]
profile = "black"
line_length = 88

[tool.flake8]
max-line-length = 88
exclude = [
"venv",
"__pycache__",
"build"
,"dist"
]
ignore = [
    "W503",
    "E203"
]