name: CI/CD Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci-checks:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ${{ secrets.TEST_DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.TEST_DB_PASS }}
          POSTGRES_DB: ${{ secrets.TEST_DB}}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgresql://testuser:testpass@localhost:5432/mydatabase

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dev dependencies
      run: |
        pip install -r requirements-dev.txt
        pip install isort black flake8

    - name: Run isort
      run: isort . --check-only

    - name: Run Black
      run: black . --check

    - name: Run Flake8
      run: flake8 app app/tests

    - name: Run Tests
      run: pytest --disable-warnings

  docker-deploy:
    needs: ci-checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Extract version from Git tag
      id: get_version
      run: |
        VERSION=$(git describe --tags --abbrev=0 || echo "v0.0.0")
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          agprofessional/app-tracker-private:latest
          agprofessional/app-tracker-private:${{ env.VERSION }}
